name: uae_city_areas
description: A Flutter plugin for fetching cities/emirates and areas from UAE API with persistent caching support.
version: 1.0.0+2
repository: https://github.com/XeroDays/uae_city_areas.git
homepage: https://github.com/XeroDays/uae_city_areas

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
